### ISSUE TITLE
muc.createInstantRoom always throws an unknown error

### ISSUE THREAD

**Issue by oladipo** [strophe/strophejs-plugin-muc#4]
when i call connection.muc.createInstantRoom(roomName, sucess_cb, failure_cb);

I always get the failure_cb called back with an unknown error.

How do i know what the error messsage is..

already tried console.log.

Is there any sample implmentation out there.. a complete one i mean.. thanks

**Comment by sualko** [comment]
The `failure_cb` should contain the returned error stanza as first argument.

I used this plugin in https://github.com/jsxc/jsxc/blob/master/src/jsxc.lib.muc.js.

**Comment by oladipo** [comment]
that's the problem.. its always null....

**Comment by oladipo** [comment]
Ooops! it works now..
