### ISSUE TITLE
Delete a Chat room

### ISSUE THREAD

**Issue by mailtosagar** [strophe/strophejs-plugin-muc#7]
Hi All,
How can i delete a room using the strophejs-plugin-muc. 

Also i want to know that whether it is recommended to use strophejs-plugin-muc or to send XML for group chats .

**Comment by sualko** [comment]
> How can i delete a room using the strophejs-plugin-muc.

I don't know what you mean by "delete" but if you like to destroy a room, have a look at the XEP: https://xmpp.org/extensions/xep-0045.html#destroyroom

> whether it is recommended to use strophejs-plugin-muc or to send XML for group chats

That's up to you.
