### ISSUE TITLE
Not receiving stanzas on running connection.muc.createConfiguredRoom()

### ISSUE THREAD

**Issue by mailtosagar** [strophe/strophejs-plugin-muc#8]
Hi ,
I am using this plugin and code i am using is 

groupName = groupName+'@conference.localhost'
  conn.muc.join(groupName, conn.jid, group_msg_handler, group_pres_handler);
  var config = {"muc#roomconfig_publicroom": "1", "muc#roomconfig_persistentroom": "1"};
  if (descr)  config["muc#roomconfig_roomdesc"] = descr;
  if (subject)  config["muc#roomconfig_subject"] = subject;
  conn.muc.createConfiguredRoom(groupName, config, (stanza) => dispatch(onCreateRoomSuccess(stanza)), (stanza) => (onCreateRoomError(stanza, groupName)));

I am not receiving the conformation stanzas from the server. 
I am using ejabberd.

**Comment by sualko** [comment]
You are calling `createConfiguredRoom` too early. Please check the corresponding MUC and your outgoing and incoming stanzas.
